# Local ffuf image for the containerised content-discovery tool.
# Built locally (not pulled) and pinned, same rationale as sqlmap.Dockerfile:
# no untrusted image in the supply chain, the tool lives only in a throwaway
# Linux container (never on host disk where AV quarantines it), version-pinned.
#
#   docker build -t harness/ffuf:2.1.0 -f tools/ffuf.Dockerfile tools
#
# The harness invokes it via ffuf_runner (tool_runner.run("harness/ffuf:2.1.0", ...)).
# The wordlist is baked in at /wordlist.txt (generated by gen_ffuf_wordlist.py from
# the harness's own vocabulary), so the fuzz candidate set is versioned + auditable
# with the image. Scope (target URL) and identity headers are passed by the harness
# at run time, never baked in.
FROM golang:1.22-bookworm AS build
RUN go install github.com/ffuf/ffuf/v2@v2.1.0

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /go/bin/ffuf /usr/local/bin/ffuf
COPY ffuf-wordlist.txt /wordlist.txt
RUN useradd -m runner
USER runner
ENTRYPOINT ["ffuf"]
